### ISSUE TITLE
Adjust task list to let users focus on open tasks

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/hub#550]
- [x] new step order --> to motivate users to deposit 
1. Open first channel
2. Make your first deposit
3. Connect your first app
4. Make your first payment
5. Backup your wallet

- [ ] Remove the step when done --> to make it look less cluttered instead of using strikethrough
e.g. Connect Alby account

- [ ] Add step back again to the list when not done --> to remind users that there is something left to do

**Comment by reneaaron** [comment]
Closing as we did many iterations and I think the current state pretty much covers what we wanted to address here.
